apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: form-ingress
  annotations:
    # kubernetes.io/ingress.class: traefik
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: devops.k8s
      http:
        paths:
          - path: /
            backend:
              serviceName: form
              servicePort: 8080

          
