apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-search
spec:
  serviceName: elastic-search
  replicas: 1
  selector:
   matchLabels: 
     app: elastic-search
  template:
    metadata:
      labels:
        app: elastic-search
    spec:
      containers:
      - name: elastic-search
        image: blacktop/elasticsearch:7.3
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m 
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: es-data 
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: cluster.name
          value: elastic-cluster
        - name: node.name
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "elastic-search-0.elastic-cluster"
        - name: cluster.initial_master_nodes
          value: "elastic-search-0"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xms512m"
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh","-c","chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data 
   #     - name: increase-vm-max-map
   #       image: busybox
   #       command: ["sysctl","-w","vm.max_map_count=262144"]
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh","-c","ulimit -n 65536"]
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi

             
     

