apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system 
  labels:
    app: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: fluentd
        image: azimuth3d/fluentd-es
        imagePullPolicy: Always
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elastic-search"


