apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: "kibana"
          image: blacktop/kibana:7.3
          resources:
              limits:
                cpu: 1000m
                memory:  512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          env:
          - name: ELASTIC_SEARCH_HOST
            value: http://elastic-search:9200
          ports:
          - containerPort: 5601
          
          
